# Generated by Django 2.0.12 on 2020-02-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=64, verbose_name='CustomerName')),
                ('ContactName', models.CharField(max_length=64, verbose_name='ContactName')),
                ('Address', models.CharField(max_length=64, verbose_name='Addres')),
                ('City', models.CharField(max_length=64, verbose_name='City')),
                ('PostalCode', models.CharField(max_length=64, verbose_name='PostalCode')),
                ('Country', models.CharField(max_length=64, verbose_name='Country')),
            ],
        ),
    ]
