# Generated by Django 2.0.12 on 2020-02-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=64, verbose_name='SupplierName')),
                ('ContactName', models.CharField(max_length=64, verbose_name='ContactName')),
                ('Address', models.CharField(max_length=64, verbose_name='Address')),
                ('City', models.CharField(max_length=64, verbose_name='City')),
                ('PostalCode', models.CharField(max_length=64, verbose_name='PostalCode')),
                ('Country', models.CharField(max_length=50, verbose_name='Country')),
                ('Phone', models.IntegerField(verbose_name='Phone')),
            ],
        ),
    ]
