# Generated by Django 3.0.3 on 2020-03-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('Shipper', '0002_auto_20200229_1938'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipper.Shipper'),
        ),
    ]
